### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Lim9er** [racaljk/sparrow#3]
You should really take effort in English :-)

**Comment by racaljk** [comment]
show me your revision

**Comment by lbwawrence** [comment]
Kidding.
其实我觉得注意一下大小写就好 顺便改一下拼写错误，不多的

**Comment by racaljk** [comment]
I have to write many tutorials and demos when new feature released so that users could follow official tutorials step by step, it's inevitable to leave many typos and syntax problem, i'll fix them in later relrases
